<?php

class NotebookProduct extends Product implements IGadget
{
    public $cpu;

    public function __construct($name, $price, $cpu)
    {
        parent::__construct($name, $price);
        $this->cpu = $cpu;
    }

    public function getGadget()
    {
        // TODO: Implement getGadget() method.
    }

    public function addProduct($name, $price)
    {
        // TODO: Implement addProduct() method.
    }

    public function getProduct()
    {
        $out = parent::getProduct(); // TODO: Change the autogenerated stub
        $out .= "<strong>Processor</strong>: $this->cpu<br>";
        return $out;
    }

    public function getCpu()
    {
        return $this->cpu;
    }
}